{% set name = "praw" %}
{% set import = "praw" %}
{% set version = "7.8.0" %}
{% set sha256 = "910a1478d79ce3892bf35b2c52c90f575d6618dfce248e7bf90eed354c19589c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - prawcore >=2.1,<3
    - update_checker >=0.18
    - websocket-client >=0.54.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - {{ import }}

about:
  home: https://praw.readthedocs.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Reddit API Wrapper allows for simple access to Reddit's API
  description: |
    PRAW, an acronym for "Python Reddit API Wrapper", is a python package that
    allows for simple access to Reddit's API. PRAW aims to be easy to use and
    internally follows all of Reddit's API rules. With PRAW there's no need to
    introduce sleep calls in your code. Give your client an appropriate user
    agent and you're set.
  doc_url: https://praw.readthedocs.io/
  dev_url: https://github.com/praw-dev/praw

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - djsutherland
